name: App Resharper

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ feature ]

jobs:
  analyze:
    name: Resharper
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Resharper
        uses: goit/setup-resharper@v1
        with:
          version: '2021.1'
          run: InspectCode Senselessly.Foolish.Bethesda.sln